apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: hello-world-preprod
  labels:
    environment: preprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      environment: preprod
  template:
    metadata:
      labels:
        app: backend
        environment: preprod
    spec:
      containers:
      - name: backend
        image: ghcr.io/joaolmonteiro/eks_hello_world_backend/hello-world_back:latest
        ports:
        - containerPort: 3000
